name: Build

on:
  repository_dispatch:
    types: [repo-released]

jobs:

  build:
    name: Build and Publish Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          ref: ${{ github.event.client_payload.ref }}
          token: ${{ secrets.SOURCE_REPO_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Hexagon
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          tags: hexagon:latest
          load: true
          build-args: |
            ARTIFACT_TAG={{ github.event.client_payload.tag_name }}

      - name: Extract artifacts
        id: extract1
        uses: shrink/actions-docker-extract@v1
        with:
          image: hexagon:latest
          path: /usr/local/hexagon-artifacts

      - name: Setup jFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}

      - name: Publish artifacts
        run: | 
          jfrog --version
          jfrog rt ping
          cd ${{ steps.extract1.outputs.destination }}
          jfrog rt u "/*" codelinaro-toolchain-for-hexagon
        
