name: Build

on:
  repository_dispatch:
    types: [repo-released]

jobs:

  build:
    name: Build and Publish Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          ref: ${{ github.event.client_payload.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Hexagon
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.build
          tags: hexagon:latest
          load: true

      - name: Extract file 1
        id: extract1
        uses: shrink/actions-docker-extract@v1
        with:
          image: hexagon:latest
          path: /app/results/

      - name: Setup jFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}

      - name: Publish file
        run: | 
          jfrog --version
          jfrog rt ping
          jfrog rt u "${{ steps.extract1.outputs.destination }}/*.txt" codelinaro-toolchain-for-hexagon
        