name: Build

on:
  repository_dispatch:
    types: [repo-released]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          ref: ${{ github.event.client_payload.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Hexagon
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.build
          tags: hexagon:latest
          load: true

      - name: Extract file 1
        id: extract1
        uses: shrink/actions-docker-extract@v1
        with:
          image: hexagon:latest
          path: /app/file1.txt

      - name: Print file 1   
        run: |
          echo "${{ steps.extract1.outputs.destination }}/file1.txt"
          cat ${{ steps.extract1.outputs.destination }}/file1.txt

      - name: Setup jFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}

      - name: Publish file 1
        run: | 
          jfrog --version
          jfrog rt ping
        